-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 14:30:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tokai-rika-ph
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tokai-rika-ph
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tokai-rika-ph` DEFAULT CHARACTER SET utf8 ;
USE `tokai-rika-ph` ;

-- -----------------------------------------------------
-- Table `tokai-rika-ph`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokai-rika-ph`.`person` (
  `id` INT NOT NULL DEFAULT index,
  `first name` VARCHAR(45) NOT NULL,
  `middle name` VARCHAR(45) NULL,
  `last name` VARCHAR(45) NOT NULL,
  `contact number` VARCHAR(45) NULL,
  `address` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `birthday` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokai-rika-ph`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokai-rika-ph`.`supplier` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokai-rika-ph`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokai-rika-ph`.`company` (
  `id` INT NOT NULL DEFAULT index,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokai-rika-ph`.`representative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokai-rika-ph`.`representative` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`, `company_id`),
  INDEX `fk_representative_company_idx` (`company_id` ASC) VISIBLE,
  INDEX `fk_representative_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_representative_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `tokai-rika-ph`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_representative_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `tokai-rika-ph`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokai-rika-ph`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokai-rika-ph`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `supplier_id` INT NOT NULL,
  `representative_id` INT NOT NULL,
  `representative_company_id` INT NOT NULL,
  PRIMARY KEY (`id`, `supplier_id`, `representative_id`, `representative_company_id`),
  INDEX `fk_department_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_department_representative1_idx` (`representative_id` ASC, `representative_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_department_supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `tokai-rika-ph`.`supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_department_representative1`
    FOREIGN KEY (`representative_id` , `representative_company_id`)
    REFERENCES `tokai-rika-ph`.`representative` (`id` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokai-rika-ph`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokai-rika-ph`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tokai-rika-ph`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tokai-rika-ph`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `position_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`, `department_id`, `position_id`),
  INDEX `fk_employee_department1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_employee_position1_idx` (`position_id` ASC) VISIBLE,
  INDEX `fk_employee_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `tokai-rika-ph`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `tokai-rika-ph`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `tokai-rika-ph`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
